spring.application.name=fitness-app

# server
server.servlet.context-path=/aos
server.port=8080

# app
# App configuration
app.name=Fitness App

## logging
# Root logging level
logging.level.root=INFO

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/AOS
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.security.enabled=false

#Security
application.security.jwt.secret-key=cng5thX/P3wuVcreImOPHrT4XUR1DIkCZFxapXGqlxBP+jC0oB92FlrgX8rD6pRR
application.security.jwt.expiration=864000
whitelist.urls=/auth/**,/h2-console/**,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html
secured-url=/test/**


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=za.elsharkawy@gmail.com
spring.mail.password=fzrs ffxj zkmw qwym
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com




#Produciton configs
#TODO: to be uncommented
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=false

